mujoco_sim_ros2_node:
  ros__parameters:
    model_package: wobl_description
    model_file: 'mjcf/plane_world.xml'
    physics_plugins:
      - 'mujoco_ros2_control::MujocoRos2ControlPlugin'

controller_manager:
  ros__parameters:
    update_rate: 80  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController

    pid_balance_controller:
      type: wobl_controllers/PidBalanceController

velocity_controller:
  ros__parameters:
    joints:
      - L_hip
      - R_hip
      - L_foot
      - R_foot
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

position_controller:
  ros__parameters:
    joints:
      - L_hip
      - R_hip
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity